### ISSUE TITLE
feature requst: web interface?

### ISSUE THREAD

**Issue by Jiffies-Duke** [mescanne/goledger#1]
I do like this awesome goledger. Great work!
Do you have any plan to implement a web interface, like [fava](https://github.com/beancount/fava) ?

**Comment by mescanne** [comment]
No plans. I was thinking more PDF or HTML generated reports. Once you have HTML generated reports, extending it to have a web interface to generate/configure reports and see the HTML (or text or PDF) immediately would be the next step.

**Comment by Jiffies-Duke** [comment]
> PDF or HTML generated reports .....

Good idea! HTML or PDF reports with charts and graphs are actually what most users (I thought) want, instead of running a web interface only to see that.
