### ISSUE TITLE
Compilation error:

### ISSUE THREAD

**Issue by pedroalbanese** [mescanne/goledger#12]
I'm getting the following error:

book\book_accum.go:36:30: constant 1000000000000000 overflows int

What I'm doing wrong?

Thanks in advance.

**Comment by mescanne** [comment]
You must be compiling on a 32-bit architecture. Arm32? It's been forced to a 64bit integer in either case and should compile now.

**Comment by pedroalbanese** [comment]
I'm compiling on Windows 32-bits. Now it compiled, but I can't find the file goledger.toml.. Any idea?
