### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by jonszcz** [mescanne/goledger#3]
I'm getting two separate errors when I try to install. The first is that there isn't a valid hostname. I seem to be able to get past this by adding `.com` after github in the `go get ...`. But then I get this warning without the program installing.

` /github.com/mescanne/goledger/cmd/app/print.go:126:17: error: reference to undefined identifier ‘strings.ReplaceAll’
   num = strings.ReplaceAll(num, "  ", " ·")`

Any thoughts would be appreciated.

**Comment by mescanne** [comment]
Likely an issue of the version of go. I'm using 1.13 and it looks like strings.ReplaceAll was introduced in 1.12.

I strongly suggest upgrading to 1.13.

**Comment by jonszcz** [comment]
That did the job. Thanks so much for the help.
