### ISSUE TITLE
feature request - support account aliases

### ISSUE THREAD

**Issue by jnflint** [mescanne/goledger#4]
Can support be added for account aliases?

Either as a sub directive like the example in the manual: 
```
account Expenses:Food
    note This account is all about the chicken!
    alias food
    payee ^(KFC|Popeyes)$
    check commodity == "$"
    assert commodity == "$"
    eval print("Hello!")
    default
```
Or as a separate line item, example below also from ledger manual:

```
alias Dining=Expenses:Entertainment:Dining
alias Checking=Assets:Credit Union:Joint Checking Account

2011/11/28 YummyPalace
    Dining        $10.00
    Checking
```

Additional non related request is for reports to spit out JSON as this would make it easy to format in different ways such as generate static web page etc.

**Comment by mescanne** [comment]
I've added JSON documentation generation for the report.  Not for register, though.

More flexible output to webpages, PDF, etc is a good challenge. My preference would be for goledger to provide a very sensible good output baked into the binary with some good configuration points. For example:
 - Generated HTML has a very straight forward structure with associated classes
 - Builtin CSS renders it in a decent/nice way. This can be included inline'd in the generated output. (Keep it simple - something to email, all one file).
 - Configuration file can point to external CSS file that can be inline'd in the generation as an alternative.

If you come up with an HTML report structure and sample CSS, it would be greatly appreciated.

I'll look to add account aliases sometime soon. I would have the alias only be valid for the current ledger file being parsed (not anything included), and it would lose the information once loaded.

Would you need the alias to be valid across ledger files?

**Comment by mescanne** [comment]
Try it now. I've added alias for accounts (including included-files -- needs to be tested), as well as a sample HTML page generation with customised CSS as an option.

**Comment by jnflint** [comment]
Thanks, am getting error: show_transactions.go:93:18: undefined: utils.GetFileOrStr
perhaps util.go was not committed?
I'll test with my ledger file when working

**Comment by mescanne** [comment]
Try again.
